### PR TITLE
Password Generator Added

### PR DESCRIPTION
**Pull request by ayushmankumar7**

### CODE REVIEW

**Comment by carlzoo** [comment]
This is not safe for security usage.

**Comment by ayushmankumar7** [comment]
Okay. Lemme See what i can do

**Comment by Expire0** [comment]
there are some errors in the code under Python3 . Maybe you need to iterate through the dict?
    260         except ValueError:
    261             raise IndexError('Cannot choose from an empty sequence') from None
--> 262         return seq[i]
    263 
    264     def shuffle(self, x, random=None):

TypeError: 'dict_keys' object is not subscriptable

**Comment by Expire0** [comment]
> Okay. Lemme See what i can do

based of your intial code . consider this as it seem to work with Python3
def generate_pass(length=21):
    """Function to generate a password"""

    password = []

    while len(password) < length:
        key = choice([char_set["small"],char_set["big"],char_set["special"],char_set["nums"]])
        a_char = urandom(1)
        n = choice(key)
        if n in key:
            if check_prev_char(password, n):
                continue
            else:
                password.append(n)
    return ''.join(password)

**Comment by ayushmankumar7** [comment]
Thanks for the help. Should i PR once again?

**Comment by Expire0** [comment]
This looks good. Thank you .. approving the PR

**Pull request merged**
